package org.talend.designer.codegen.translators.internet.ftp;

import org.talend.core.model.process.INode;
import org.talend.core.model.process.ElementParameterParser;
import org.talend.designer.codegen.config.CodeGeneratorArgument;
import java.util.List;

public class TFTPPutMainJava
{
  protected static String nl;
  public static synchronized TFTPPutMainJava create(String lineSeparator)
  {
    nl = lineSeparator;
    TFTPPutMainJava result = new TFTPPutMainJava();
    nl = null;
    return result;
  }

  public final String NL = nl == null ? (System.getProperties().getProperty("line.separator")) : nl;
  protected final String TEXT_1 = "";
  protected final String TEXT_2 = NL + "try{";
  protected final String TEXT_3 = NL + "        globalMap.put(\"";
  protected final String TEXT_4 = "_CURRENT_STATUS\", \"No file transfered.\");" + NL + "        java.util.Set<String> keySet";
  protected final String TEXT_5 = " = map";
  protected final String TEXT_6 = ".keySet();" + NL + "        for (String key";
  protected final String TEXT_7 = " : keySet";
  protected final String TEXT_8 = "){" + NL + "            if(key";
  protected final String TEXT_9 = " == null || \"\".equals(key";
  protected final String TEXT_10 = ")){";
  protected final String TEXT_11 = NL + "                    log.error(\"";
  protected final String TEXT_12 = " - file name invalid!\");";
  protected final String TEXT_13 = NL + "                System.err.println(\"file name invalid!\");" + NL + "                continue;" + NL + "            }" + NL + "            String tempdir";
  protected final String TEXT_14 = " =  localdir";
  protected final String TEXT_15 = ";" + NL + "            String filemask";
  protected final String TEXT_16 = " = key";
  protected final String TEXT_17 = ";" + NL + "            String dir";
  protected final String TEXT_18 = " = null;";
  protected final String TEXT_19 = NL + "                String mask";
  protected final String TEXT_20 = " = filemask";
  protected final String TEXT_21 = ".replaceAll(\"\\\\\\\\\", \"/\") ;";
  protected final String TEXT_22 = NL + "                String mask";
  protected final String TEXT_23 = " = filemask";
  protected final String TEXT_24 = ";";
  protected final String TEXT_25 = NL + "            int i";
  protected final String TEXT_26 = " = mask";
  protected final String TEXT_27 = ".lastIndexOf('/');" + NL + "            if (i";
  protected final String TEXT_28 = "!=-1){" + NL + "                dir";
  protected final String TEXT_29 = " = mask";
  protected final String TEXT_30 = ".substring(0, i";
  protected final String TEXT_31 = ");" + NL + "                mask";
  protected final String TEXT_32 = " = mask";
  protected final String TEXT_33 = ".substring(i";
  protected final String TEXT_34 = "+1);" + NL + "            }" + NL + "            if (dir";
  protected final String TEXT_35 = "!=null && !\"\".equals(dir";
  protected final String TEXT_36 = ")) tempdir";
  protected final String TEXT_37 = " = tempdir";
  protected final String TEXT_38 = " + \"/\" + dir";
  protected final String TEXT_39 = ";";
  protected final String TEXT_40 = NL + "                mask";
  protected final String TEXT_41 = " = mask";
  protected final String TEXT_42 = ".replaceAll(\"\\\\.\", \"\\\\\\\\.\").replaceAll(\"\\\\*\", \".*\");";
  protected final String TEXT_43 = NL + "            final String finalMask";
  protected final String TEXT_44 = " = mask";
  protected final String TEXT_45 = ";" + NL + "            java.io.File[] listings";
  protected final String TEXT_46 = " = null;" + NL + "            java.io.File file";
  protected final String TEXT_47 = " = new java.io.File(tempdir";
  protected final String TEXT_48 = ");" + NL + "            if (file";
  protected final String TEXT_49 = ".isDirectory()) {" + NL + "                listings";
  protected final String TEXT_50 = " = file";
  protected final String TEXT_51 = ".listFiles(new java.io.FileFilter() {" + NL + "                    public boolean accept(java.io.File pathname) {" + NL + "                        boolean result = false;" + NL + "                        if (pathname != null && pathname.isFile()) {" + NL + "                                result = java.util.regex.Pattern.compile(finalMask";
  protected final String TEXT_52 = ").matcher(pathname.getName()).find();" + NL + "                            }" + NL + "                        return result;" + NL + "                    }" + NL + "                });" + NL + "            }" + NL + "            if(listings";
  protected final String TEXT_53 = " != null && listings";
  protected final String TEXT_54 = ".length > 0){" + NL + "                for (int m";
  protected final String TEXT_55 = " = 0; m";
  protected final String TEXT_56 = " < listings";
  protected final String TEXT_57 = ".length; m";
  protected final String TEXT_58 = "++){" + NL + "                    if (listings";
  protected final String TEXT_59 = "[m";
  protected final String TEXT_60 = "].getName().matches(mask";
  protected final String TEXT_61 = ")){" + NL;
  protected final String TEXT_62 = NL + "                        int mode";
  protected final String TEXT_63 = " = com.jcraft.jsch.ChannelSftp.OVERWRITE;";
  protected final String TEXT_64 = NL + "                        int mode";
  protected final String TEXT_65 = " = com.jcraft.jsch.ChannelSftp.APPEND;";
  protected final String TEXT_66 = NL + "                        int mode";
  protected final String TEXT_67 = " = com.jcraft.jsch.ChannelSftp.RESUME;";
  protected final String TEXT_68 = NL + "                        try{" + NL + "                            c_";
  protected final String TEXT_69 = ".put(listings";
  protected final String TEXT_70 = "[m";
  protected final String TEXT_71 = "].getAbsolutePath(), ";
  protected final String TEXT_72 = ", monitor";
  protected final String TEXT_73 = ", mode";
  protected final String TEXT_74 = ");" + NL + "" + NL + "                            // add info to list will return" + NL + "                            msg_";
  protected final String TEXT_75 = ".add(\"file: \" + listings";
  protected final String TEXT_76 = "[m";
  protected final String TEXT_77 = "].getAbsolutePath() + \", size: \"" + NL + "                                + listings";
  protected final String TEXT_78 = "[m";
  protected final String TEXT_79 = "].length() + \" bytes upload successfully\");";
  protected final String TEXT_80 = NL + "                                log.debug(\"";
  protected final String TEXT_81 = " - Uploaded file '\" + listings";
  protected final String TEXT_82 = "[m";
  protected final String TEXT_83 = "].getName() + \"' successfully.\");";
  protected final String TEXT_84 = NL + "                            globalMap.put(\"";
  protected final String TEXT_85 = "_CURRENT_STATUS\", \"File transfer OK.\");" + NL + "                            if(c_";
  protected final String TEXT_86 = ".stat(";
  protected final String TEXT_87 = "+\"/\"+listings";
  protected final String TEXT_88 = "[m";
  protected final String TEXT_89 = "].getName()).getAtimeString() != null){" + NL + "                                globalMap.put(\"";
  protected final String TEXT_90 = "_CURRENT_FILE_EXISTS\",true);" + NL + "                            }" + NL + "                        }catch(com.jcraft.jsch.SftpException e_";
  protected final String TEXT_91 = ") {";
  protected final String TEXT_92 = NL + "                                log.error(\"";
  protected final String TEXT_93 = " - File transfer fail.\"+e_";
  protected final String TEXT_94 = ".getMessage());";
  protected final String TEXT_95 = NL + "                            globalMap.put(\"";
  protected final String TEXT_96 = "_CURRENT_STATUS\", \"File transfer fail.\");" + NL + "                            if(c_";
  protected final String TEXT_97 = ".stat(";
  protected final String TEXT_98 = "+\"/\"+listings";
  protected final String TEXT_99 = "[m";
  protected final String TEXT_100 = "].getName()).getAtimeString() != null){" + NL + "                                globalMap.put(\"";
  protected final String TEXT_101 = "_CURRENT_FILE_EXISTS\",true);" + NL + "                            }";
  protected final String TEXT_102 = NL + "                            throw(e_";
  protected final String TEXT_103 = ");";
  protected final String TEXT_104 = NL + "                                log.error(\"";
  protected final String TEXT_105 = " - File permission denied: \"+";
  protected final String TEXT_106 = "+\"/\"+listings";
  protected final String TEXT_107 = "[m";
  protected final String TEXT_108 = "].getName());";
  protected final String TEXT_109 = NL + "                            System.err.println(\"File permission denied: \"+";
  protected final String TEXT_110 = "+\"/\"+listings";
  protected final String TEXT_111 = "[m";
  protected final String TEXT_112 = "].getName());";
  protected final String TEXT_113 = NL + "                        }catch(java.lang.Exception e_";
  protected final String TEXT_114 = "){" + NL + "                           if(!(e_";
  protected final String TEXT_115 = " instanceof com.jcraft.jsch.SftpException)) {" + NL + "                                msg_";
  protected final String TEXT_116 = ".add(\"file \" + listings";
  protected final String TEXT_117 = "[m";
  protected final String TEXT_118 = "].getAbsolutePath() + \" not found?\");" + NL + "" + NL + "                                globalMap.put(\"";
  protected final String TEXT_119 = "_CURRENT_FILE_EXISTS\",false);" + NL + "                            }" + NL + "                            throw e_";
  protected final String TEXT_120 = ";" + NL + "                        }" + NL + "                        nb_file_";
  protected final String TEXT_121 = "++;" + NL + "                    }" + NL + "                }" + NL + "            }else{";
  protected final String TEXT_122 = NL + "                    log.error(\"";
  protected final String TEXT_123 = " - No match file exist!\");";
  protected final String TEXT_124 = NL + "                System.err.println(\"No match file exist!\");" + NL + "            }" + NL + "" + NL + "            //do rename" + NL + "            if(map";
  protected final String TEXT_125 = ".get(key";
  protected final String TEXT_126 = ") != \"\" && key";
  protected final String TEXT_127 = " != map";
  protected final String TEXT_128 = ".get(key";
  protected final String TEXT_129 = ")){";
  protected final String TEXT_130 = NL + "                    try{" + NL + "                        c_";
  protected final String TEXT_131 = ".rm(";
  protected final String TEXT_132 = "+\"/\"+map";
  protected final String TEXT_133 = ".get(key";
  protected final String TEXT_134 = "));" + NL + "                    }catch(com.jcraft.jsch.SftpException e_";
  protected final String TEXT_135 = "){" + NL + "                    }";
  protected final String TEXT_136 = NL + "                try{" + NL + "                    c_";
  protected final String TEXT_137 = ".rename(";
  protected final String TEXT_138 = "+\"/\"+key";
  protected final String TEXT_139 = ", ";
  protected final String TEXT_140 = "+\"/\"+map";
  protected final String TEXT_141 = ".get(key";
  protected final String TEXT_142 = "));" + NL + "                    globalMap.put(\"";
  protected final String TEXT_143 = "_CURRENT_STATUS\", \"File rename OK.\");" + NL + "                }catch(com.jcraft.jsch.SftpException e_";
  protected final String TEXT_144 = "){" + NL + "                    globalMap.put(\"";
  protected final String TEXT_145 = "_CURRENT_STATUS\", \"File rename fail.\");" + NL + "                    throw e_";
  protected final String TEXT_146 = ";" + NL + "                }" + NL + "            }" + NL + "        }" + NL + NL;
  protected final String TEXT_147 = NL + NL + "        String currentStatus_";
  protected final String TEXT_148 = " = \"No file transfered.\";" + NL + "        java.util.Set<String> keySet";
  protected final String TEXT_149 = " = map";
  protected final String TEXT_150 = ".keySet();" + NL + "        for (String key";
  protected final String TEXT_151 = " : keySet";
  protected final String TEXT_152 = "){" + NL + "            if(key";
  protected final String TEXT_153 = " == null || \"\".equals(key";
  protected final String TEXT_154 = ")){" + NL + "                System.err.println(\"file name invalid!\");";
  protected final String TEXT_155 = NL + "                    log.error(\"";
  protected final String TEXT_156 = " - file name invalid!\");";
  protected final String TEXT_157 = NL + "                continue;" + NL + "            }" + NL + "            String tempdir";
  protected final String TEXT_158 = " =  localdir";
  protected final String TEXT_159 = ";" + NL + "            String filemask";
  protected final String TEXT_160 = " = key";
  protected final String TEXT_161 = ";" + NL + "            String dir";
  protected final String TEXT_162 = " = null;";
  protected final String TEXT_163 = NL + "                String mask";
  protected final String TEXT_164 = " = filemask";
  protected final String TEXT_165 = ".replaceAll(\"\\\\\\\\\", \"/\") ;";
  protected final String TEXT_166 = NL + "                String mask";
  protected final String TEXT_167 = " = filemask";
  protected final String TEXT_168 = ";";
  protected final String TEXT_169 = NL + "            int i";
  protected final String TEXT_170 = " = mask";
  protected final String TEXT_171 = ".lastIndexOf('/');" + NL + "            if (i";
  protected final String TEXT_172 = "!=-1){" + NL + "                dir";
  protected final String TEXT_173 = " = mask";
  protected final String TEXT_174 = ".substring(0, i";
  protected final String TEXT_175 = ");" + NL + "                mask";
  protected final String TEXT_176 = " = mask";
  protected final String TEXT_177 = ".substring(i";
  protected final String TEXT_178 = "+1);" + NL + "            }" + NL + "            if (dir";
  protected final String TEXT_179 = "!=null && !\"\".equals(dir";
  protected final String TEXT_180 = ")){" + NL + "                tempdir";
  protected final String TEXT_181 = " = tempdir";
  protected final String TEXT_182 = " + \"/\" + dir";
  protected final String TEXT_183 = ";" + NL + "            }";
  protected final String TEXT_184 = NL + "                mask";
  protected final String TEXT_185 = " = mask";
  protected final String TEXT_186 = ".replaceAll(\"\\\\.\", \"\\\\\\\\.\").replaceAll(\"\\\\*\", \".*\");";
  protected final String TEXT_187 = NL + "            final String finalMask";
  protected final String TEXT_188 = " = mask";
  protected final String TEXT_189 = ";" + NL + "            java.io.File[] listings";
  protected final String TEXT_190 = " = null;" + NL + "            java.io.File file";
  protected final String TEXT_191 = " = new java.io.File(tempdir";
  protected final String TEXT_192 = ");" + NL + "            if (file";
  protected final String TEXT_193 = ".isDirectory()) {" + NL + "                listings";
  protected final String TEXT_194 = " = file";
  protected final String TEXT_195 = ".listFiles(new java.io.FileFilter() {" + NL + "                    public boolean accept(java.io.File pathname) {" + NL + "                        boolean result = false;" + NL + "                        if (pathname != null && pathname.isFile()) {" + NL + "                                result = java.util.regex.Pattern.compile(finalMask";
  protected final String TEXT_196 = ").matcher(pathname.getName()).find();" + NL + "                            }" + NL + "                        return result;" + NL + "                        }" + NL + "                    });" + NL + "            }" + NL + "            if(listings";
  protected final String TEXT_197 = " != null && listings";
  protected final String TEXT_198 = ".length > 0){" + NL + "                for (int m";
  protected final String TEXT_199 = " = 0; m";
  protected final String TEXT_200 = " < listings";
  protected final String TEXT_201 = ".length; m";
  protected final String TEXT_202 = "++){" + NL + "                            java.io.File file_in_localDir = listings";
  protected final String TEXT_203 = "[m";
  protected final String TEXT_204 = "];" + NL + "                            String uploadingFileName_";
  protected final String TEXT_205 = " = file_in_localDir.getName();" + NL + "                    String newFileName_";
  protected final String TEXT_206 = " = map";
  protected final String TEXT_207 = ".get(key";
  protected final String TEXT_208 = ");" + NL + "                    String newName_";
  protected final String TEXT_209 = " = (\"\".equals(newFileName_";
  protected final String TEXT_210 = ")) ? uploadingFileName_";
  protected final String TEXT_211 = " : newFileName_";
  protected final String TEXT_212 = ";" + NL + "                    boolean targetFileExistsOnRemoteServer_";
  protected final String TEXT_213 = " = false;" + NL + "                    try{" + NL + "                        if (uploadingFileName_";
  protected final String TEXT_214 = ".matches(mask";
  protected final String TEXT_215 = ")){";
  protected final String TEXT_216 = NL + "                               targetFileExistsOnRemoteServer_";
  protected final String TEXT_217 = " = ftp_";
  protected final String TEXT_218 = ".existsFile(newName_";
  protected final String TEXT_219 = ");" + NL + "                               globalMap.put(\"";
  protected final String TEXT_220 = "_CURRENT_FILE_EXISTS\", targetFileExistsOnRemoteServer_";
  protected final String TEXT_221 = ");";
  protected final String TEXT_222 = NL + "                                ftp_";
  protected final String TEXT_223 = ".put(tempdir";
  protected final String TEXT_224 = " + \"/\" + uploadingFileName_";
  protected final String TEXT_225 = ", newName_";
  protected final String TEXT_226 = ", true);";
  protected final String TEXT_227 = NL + "                            if(!targetFileExistsOnRemoteServer_";
  protected final String TEXT_228 = "){" + NL + "                                ftp_";
  protected final String TEXT_229 = ".put(tempdir";
  protected final String TEXT_230 = " + \"/\" + uploadingFileName_";
  protected final String TEXT_231 = ", newName_";
  protected final String TEXT_232 = ");" + NL + "                            }";
  protected final String TEXT_233 = NL + "                                ftp_";
  protected final String TEXT_234 = ".put(tempdir";
  protected final String TEXT_235 = " + \"/\" + uploadingFileName_";
  protected final String TEXT_236 = ", newName_";
  protected final String TEXT_237 = ");";
  protected final String TEXT_238 = NL + "                                if (targetFileExistsOnRemoteServer_";
  protected final String TEXT_239 = "){" + NL + "                                    com.enterprisedt.net.ftp.FTPFile ftpfile";
  protected final String TEXT_240 = "=ftp_";
  protected final String TEXT_241 = ".fileDetails(newName_";
  protected final String TEXT_242 = ");" + NL + "                                    long ftpSize";
  protected final String TEXT_243 = "=ftpfile";
  protected final String TEXT_244 = ".size();" + NL + "                                    long localSize";
  protected final String TEXT_245 = "=file_in_localDir.length();" + NL + "                                    if(ftpSize";
  protected final String TEXT_246 = " != localSize";
  protected final String TEXT_247 = "){" + NL + "                                        ftp_";
  protected final String TEXT_248 = ".put(tempdir";
  protected final String TEXT_249 = " + \"/\" + uploadingFileName_";
  protected final String TEXT_250 = ", newName_";
  protected final String TEXT_251 = ");" + NL + "                                    }" + NL + "                                }else{" + NL + "                                    ftp_";
  protected final String TEXT_252 = ".put(tempdir";
  protected final String TEXT_253 = " + \"/\" + uploadingFileName_";
  protected final String TEXT_254 = ", newName_";
  protected final String TEXT_255 = ");" + NL + "                                }";
  protected final String TEXT_256 = NL + NL + "                            currentStatus_";
  protected final String TEXT_257 = " = \"File rename OK.\";" + NL + "                            msg_";
  protected final String TEXT_258 = ".add(\"file: \" + file_in_localDir.getAbsolutePath() + \", size: \"" + NL + "                                            + file_in_localDir.length() + \" bytes upload successfully\");";
  protected final String TEXT_259 = NL + "                                log.debug(\"";
  protected final String TEXT_260 = " - Uploaded file '\" + uploadingFileName_";
  protected final String TEXT_261 = " + \"' successfully.\");";
  protected final String TEXT_262 = NL + NL + "                            nb_file_";
  protected final String TEXT_263 = "++;" + NL + "                        }" + NL + "                    }catch(com.enterprisedt.net.ftp.FTPException e_";
  protected final String TEXT_264 = "){" + NL + "" + NL + "                        msg_";
  protected final String TEXT_265 = ".add(\"file \" + file_in_localDir.getAbsolutePath() + \" not found?\");" + NL + "" + NL + "                        currentStatus_";
  protected final String TEXT_266 = " = \"File rename fail.\";" + NL + "                        globalMap.put(\"";
  protected final String TEXT_267 = "_CURRENT_FILE_EXISTS\", targetFileExistsOnRemoteServer_";
  protected final String TEXT_268 = ");" + NL + "                        throw e_";
  protected final String TEXT_269 = ";" + NL + "                    }" + NL + "                }" + NL + "            }else{";
  protected final String TEXT_270 = NL + "                    log.warn(\"";
  protected final String TEXT_271 = " - No match file exist!\");";
  protected final String TEXT_272 = NL + "                System.err.println(\"No match file exist!\");" + NL + "            }" + NL + "" + NL + "        }" + NL + "        globalMap.put(\"";
  protected final String TEXT_273 = "_CURRENT_STATUS\", currentStatus_";
  protected final String TEXT_274 = ");" + NL;
  protected final String TEXT_275 = NL + "        String currentStatus_";
  protected final String TEXT_276 = " = \"No file transfered.\";" + NL + "        globalMap.put(\"";
  protected final String TEXT_277 = "_CURRENT_STATUS\", \"No file transfered.\");" + NL + "        java.util.Set<String> keySet";
  protected final String TEXT_278 = " = map";
  protected final String TEXT_279 = ".keySet();" + NL + "        boolean needRename_";
  protected final String TEXT_280 = " = false;" + NL + "        for (String key";
  protected final String TEXT_281 = " : keySet";
  protected final String TEXT_282 = "){" + NL + "            if(key";
  protected final String TEXT_283 = " == null || \"\".equals(key";
  protected final String TEXT_284 = ")){";
  protected final String TEXT_285 = NL + "                    log.error(\"";
  protected final String TEXT_286 = " - file name invalid!\");";
  protected final String TEXT_287 = NL + "                System.err.println(\"file name invalid!\");" + NL + "                continue;" + NL + "            }" + NL + "            String tempdir";
  protected final String TEXT_288 = " =  localdir";
  protected final String TEXT_289 = ";" + NL + "            String filemask";
  protected final String TEXT_290 = " = key";
  protected final String TEXT_291 = ";" + NL + "            String dir";
  protected final String TEXT_292 = " = null;";
  protected final String TEXT_293 = NL + "                String mask";
  protected final String TEXT_294 = " = filemask";
  protected final String TEXT_295 = ".replaceAll(\"\\\\\\\\\", \"/\") ;";
  protected final String TEXT_296 = NL + "                String mask";
  protected final String TEXT_297 = " = filemask";
  protected final String TEXT_298 = ";";
  protected final String TEXT_299 = NL + "            int i";
  protected final String TEXT_300 = " = mask";
  protected final String TEXT_301 = ".lastIndexOf('/');" + NL + "            if (i";
  protected final String TEXT_302 = "!=-1){" + NL + "                dir";
  protected final String TEXT_303 = " = mask";
  protected final String TEXT_304 = ".substring(0, i";
  protected final String TEXT_305 = ");" + NL + "                mask";
  protected final String TEXT_306 = " = mask";
  protected final String TEXT_307 = ".substring(i";
  protected final String TEXT_308 = "+1);" + NL + "            }" + NL + "            if (dir";
  protected final String TEXT_309 = "!=null && !\"\".equals(dir";
  protected final String TEXT_310 = ")) tempdir";
  protected final String TEXT_311 = " = tempdir";
  protected final String TEXT_312 = " + \"/\" + dir";
  protected final String TEXT_313 = ";";
  protected final String TEXT_314 = NL + "                mask";
  protected final String TEXT_315 = " = mask";
  protected final String TEXT_316 = ".replaceAll(\"\\\\.\", \"\\\\\\\\.\").replaceAll(\"\\\\*\", \".*\");";
  protected final String TEXT_317 = NL + "            final String finalMask";
  protected final String TEXT_318 = " = mask";
  protected final String TEXT_319 = ";" + NL + "            java.io.File[] listings";
  protected final String TEXT_320 = " = null;" + NL + "            java.io.File file";
  protected final String TEXT_321 = " = new java.io.File(tempdir";
  protected final String TEXT_322 = ");" + NL + "            if (file";
  protected final String TEXT_323 = ".isDirectory()) {" + NL + "                listings";
  protected final String TEXT_324 = " = file";
  protected final String TEXT_325 = ".listFiles(new java.io.FileFilter() {" + NL + "                    public boolean accept(java.io.File pathname) {" + NL + "                        boolean result = false;" + NL + "                        if (pathname != null && pathname.isFile()) {" + NL + "                                result = java.util.regex.Pattern.compile(finalMask";
  protected final String TEXT_326 = ").matcher(pathname.getName()).find();" + NL + "                            }" + NL + "                        return result;" + NL + "                    }" + NL + "                });" + NL + "            }" + NL + "" + NL + "            java.util.List<String> remoteExistsFiles_";
  protected final String TEXT_327 = " = new java.util.ArrayList<String>();" + NL + "" + NL + "            String[] ftpFileNames_";
  protected final String TEXT_328 = " = ftp_";
  protected final String TEXT_329 = ".listNames();" + NL + "            for (String ftpFileName : ftpFileNames_";
  protected final String TEXT_330 = ") {" + NL + "                if(\"\".equals(map";
  protected final String TEXT_331 = ".get(key";
  protected final String TEXT_332 = "))){" + NL + "                    if (ftpFileName.matches(mask";
  protected final String TEXT_333 = ")) {" + NL + "                        remoteExistsFiles_";
  protected final String TEXT_334 = ".add(ftpFileName);" + NL + "                    }" + NL + "                }else{" + NL + "                    if (ftpFileName.matches(map";
  protected final String TEXT_335 = ".get(key";
  protected final String TEXT_336 = "))) {" + NL + "                        remoteExistsFiles_";
  protected final String TEXT_337 = ".add(ftpFileName);" + NL + "                    }" + NL + "                }" + NL + "            }" + NL + "" + NL + "            if(listings";
  protected final String TEXT_338 = " != null && listings";
  protected final String TEXT_339 = ".length > 0){" + NL + "                for (int m";
  protected final String TEXT_340 = " = 0; m";
  protected final String TEXT_341 = " < listings";
  protected final String TEXT_342 = ".length; m";
  protected final String TEXT_343 = "++){" + NL + "                    if (listings";
  protected final String TEXT_344 = "[m";
  protected final String TEXT_345 = "].getName().matches(mask";
  protected final String TEXT_346 = ")){" + NL + "                        java.io.File file_in_localDir_";
  protected final String TEXT_347 = " = listings";
  protected final String TEXT_348 = "[m";
  protected final String TEXT_349 = "];" + NL + "                        globalMap.put(\"";
  protected final String TEXT_350 = "_CURRENT_FILE_EXISTS\", remoteExistsFiles_";
  protected final String TEXT_351 = ".contains(file_in_localDir_";
  protected final String TEXT_352 = ".getName()));" + NL + "                        String newName_";
  protected final String TEXT_353 = " = (\"\".equals(map";
  protected final String TEXT_354 = ".get(key";
  protected final String TEXT_355 = ")))?file_in_localDir_";
  protected final String TEXT_356 = ".getName():map";
  protected final String TEXT_357 = ".get(key";
  protected final String TEXT_358 = ");";
  protected final String TEXT_359 = NL + "                            if (!(remoteExistsFiles_";
  protected final String TEXT_360 = ".contains(newName_";
  protected final String TEXT_361 = "))){" + NL + "                                needRename_";
  protected final String TEXT_362 = " = true;" + NL + "                                ftp_";
  protected final String TEXT_363 = ".upload(file_in_localDir_";
  protected final String TEXT_364 = ");";
  protected final String TEXT_365 = NL + "                                    log.debug(\"";
  protected final String TEXT_366 = " - Uploaded file '\" + newName_";
  protected final String TEXT_367 = " + \"' successfully.\");";
  protected final String TEXT_368 = NL + "                                globalMap.put(\"";
  protected final String TEXT_369 = "_CURRENT_FILE_EXISTS\", remoteExistsFiles_";
  protected final String TEXT_370 = ".contains(newName_";
  protected final String TEXT_371 = "));" + NL + "                            }";
  protected final String TEXT_372 = NL + "                            needRename_";
  protected final String TEXT_373 = " = true;" + NL + "                            if ((remoteExistsFiles_";
  protected final String TEXT_374 = ".contains(newName_";
  protected final String TEXT_375 = "))){" + NL + "                                ftp_";
  protected final String TEXT_376 = ".deleteFile(newName_";
  protected final String TEXT_377 = ");" + NL + "                            }" + NL + "                            ftp_";
  protected final String TEXT_378 = ".upload(file_in_localDir_";
  protected final String TEXT_379 = ");" + NL;
  protected final String TEXT_380 = NL + "                                log.debug(\"";
  protected final String TEXT_381 = " - Overwrote file '\" + newName_";
  protected final String TEXT_382 = " + \"' successfully.\");";
  protected final String TEXT_383 = NL + "                            globalMap.put(\"";
  protected final String TEXT_384 = "_CURRENT_FILE_EXISTS\", remoteExistsFiles_";
  protected final String TEXT_385 = ".contains(newName_";
  protected final String TEXT_386 = "));" + NL;
  protected final String TEXT_387 = NL + "                        nb_file_";
  protected final String TEXT_388 = "++;" + NL + "                    }" + NL + "                }" + NL + "            }else{";
  protected final String TEXT_389 = NL + "                    log.error(\"";
  protected final String TEXT_390 = " - No match file exist!\");";
  protected final String TEXT_391 = NL + "                System.err.println(\"No match file exist!\");" + NL + "            }" + NL + "" + NL + "            //do rename" + NL + "            if(map";
  protected final String TEXT_392 = ".get(key";
  protected final String TEXT_393 = ") != \"\" && key";
  protected final String TEXT_394 = " != map";
  protected final String TEXT_395 = ".get(key";
  protected final String TEXT_396 = ")){" + NL + "                try{" + NL + "                    if(needRename_";
  protected final String TEXT_397 = "){" + NL + "                        ftp_";
  protected final String TEXT_398 = ".rename(key";
  protected final String TEXT_399 = ", map";
  protected final String TEXT_400 = ".get(key";
  protected final String TEXT_401 = "));" + NL + "                    }" + NL + "                    globalMap.put(\"";
  protected final String TEXT_402 = "_CURRENT_STATUS\", \"File rename OK.\");" + NL + "                }catch(it.sauronsoftware.ftp4j.FTPException e_";
  protected final String TEXT_403 = "){" + NL + "                    globalMap.put(\"";
  protected final String TEXT_404 = "_CURRENT_STATUS\", \"File rename fail.\");" + NL + "                    throw e_";
  protected final String TEXT_405 = ";" + NL + "                }" + NL + "            }" + NL + "            needRename_";
  protected final String TEXT_406 = " = false;" + NL + "        }";
  protected final String TEXT_407 = NL + "    }catch(java.lang.Exception e_";
  protected final String TEXT_408 = "){";
  protected final String TEXT_409 = NL + "            throw(e_";
  protected final String TEXT_410 = ");";
  protected final String TEXT_411 = NL + "                log.error(\"";
  protected final String TEXT_412 = " - \" + e_";
  protected final String TEXT_413 = ".getMessage());";
  protected final String TEXT_414 = NL + "            System.err.print(e_";
  protected final String TEXT_415 = ".getMessage());";
  protected final String TEXT_416 = NL + "    }";
  protected final String TEXT_417 = NL;

  public String generate(Object argument)
  {
    final StringBuffer stringBuffer = new StringBuffer();
    stringBuffer.append(TEXT_1);
    
    CodeGeneratorArgument codeGenArgument = (CodeGeneratorArgument) argument;
    INode node = (INode)codeGenArgument.getArgument();
    String localdir = ElementParameterParser.getValue(node, "__LOCALDIR__");
    String cid = node.getUniqueName();
    String dieOnError = ElementParameterParser.getValue(node, "__DIE_ON_ERROR__");
    String overwrite=ElementParameterParser.getValue(node, "__OVERWRITE__");
    String sftpoverwrite=ElementParameterParser.getValue(node, "__SFTPOVERWRITE__");
    String ftpsoverwrite=ElementParameterParser.getValue(node, "__FTPSOVERWRITE__");
    String remotedir = ElementParameterParser.getValue(node, "__REMOTEDIR__");
    boolean append = ("true").equals(ElementParameterParser.getValue(node, "__APPEND__"));
    String connection = ElementParameterParser.getValue(node, "__CONNECTION__");
    String useExistingConn = ElementParameterParser.getValue(node, "__USE_EXISTING_CONNECTION__");
    boolean sftp = false;
    boolean ftps = false;
    boolean isLog4jEnabled = ("true").equals(ElementParameterParser.getValue(node.getProcess(), "__LOG4J_ACTIVATE__"));
    boolean useGlob = ("true").equals(ElementParameterParser.getValue(node, "__PERL5_REGEX__"));
    if(("true").equals(useExistingConn)){
        List<? extends INode> nodeList = node.getProcess().getGeneratingNodes();
        for(INode n : nodeList){
            if(n.getUniqueName().equals(connection)){
                sftp = ("true").equals(ElementParameterParser.getValue(n, "__SFTP__"));
                ftps = ("true").equals(ElementParameterParser.getValue(n, "__FTPS__"));
            }
        }
    }else{
        sftp = ("true").equals(ElementParameterParser.getValue(node, "__SFTP__"));
        ftps = ("true").equals(ElementParameterParser.getValue(node, "__FTPS__"));
    }

    stringBuffer.append(TEXT_2);
    
    if(sftp){ // *** sftp *** //

    stringBuffer.append(TEXT_3);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_4);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_5);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_6);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_7);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_8);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_9);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_10);
    if(isLog4jEnabled){
    stringBuffer.append(TEXT_11);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_12);
    }
    stringBuffer.append(TEXT_13);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_14);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_15);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_16);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_17);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_18);
    if(!useGlob) {//perl5 mode not support windows(\) path separator at the mask string
    stringBuffer.append(TEXT_19);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_20);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_21);
    } else {
    stringBuffer.append(TEXT_22);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_23);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_24);
    }
    stringBuffer.append(TEXT_25);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_26);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_27);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_28);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_29);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_30);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_31);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_32);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_33);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_34);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_35);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_36);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_37);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_38);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_39);
    if(!useGlob) {
    stringBuffer.append(TEXT_40);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_41);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_42);
    }
    stringBuffer.append(TEXT_43);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_44);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_45);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_46);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_47);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_48);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_49);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_50);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_51);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_52);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_53);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_54);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_55);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_56);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_57);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_58);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_59);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_60);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_61);
    if(("overwrite").equals(sftpoverwrite)){
    stringBuffer.append(TEXT_62);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_63);
    }else if(("append").equals(sftpoverwrite)){
    stringBuffer.append(TEXT_64);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_65);
    }else if(("resume").equals(sftpoverwrite)){
    stringBuffer.append(TEXT_66);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_67);
    }
    stringBuffer.append(TEXT_68);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_69);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_70);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_71);
    stringBuffer.append(remotedir);
    stringBuffer.append(TEXT_72);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_73);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_74);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_75);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_76);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_77);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_78);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_79);
    if(isLog4jEnabled){
    stringBuffer.append(TEXT_80);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_81);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_82);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_83);
    }
    stringBuffer.append(TEXT_84);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_85);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_86);
    stringBuffer.append(remotedir);
    stringBuffer.append(TEXT_87);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_88);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_89);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_90);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_91);
    if(isLog4jEnabled){
    stringBuffer.append(TEXT_92);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_93);
    stringBuffer.append( cid );
    stringBuffer.append(TEXT_94);
    }
    stringBuffer.append(TEXT_95);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_96);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_97);
    stringBuffer.append(remotedir);
    stringBuffer.append(TEXT_98);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_99);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_100);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_101);
    
                        if(("true").equals(dieOnError)){
                    
    stringBuffer.append(TEXT_102);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_103);
    
                        }else{
                    
    if(isLog4jEnabled){
    stringBuffer.append(TEXT_104);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_105);
    stringBuffer.append(remotedir);
    stringBuffer.append(TEXT_106);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_107);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_108);
    }
    stringBuffer.append(TEXT_109);
    stringBuffer.append(remotedir);
    stringBuffer.append(TEXT_110);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_111);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_112);
    
                        }
                    
    stringBuffer.append(TEXT_113);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_114);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_115);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_116);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_117);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_118);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_119);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_120);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_121);
    if(isLog4jEnabled){
    stringBuffer.append(TEXT_122);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_123);
    }
    stringBuffer.append(TEXT_124);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_125);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_126);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_127);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_128);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_129);
    
                if(("overwrite").equals(sftpoverwrite) || ("resume").equals(sftpoverwrite)){
                
    stringBuffer.append(TEXT_130);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_131);
    stringBuffer.append(remotedir );
    stringBuffer.append(TEXT_132);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_133);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_134);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_135);
    
                }
                
    stringBuffer.append(TEXT_136);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_137);
    stringBuffer.append(remotedir );
    stringBuffer.append(TEXT_138);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_139);
    stringBuffer.append(remotedir );
    stringBuffer.append(TEXT_140);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_141);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_142);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_143);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_144);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_145);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_146);
    
    }else if (!ftps) { // *** ftp *** //

    stringBuffer.append(TEXT_147);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_148);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_149);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_150);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_151);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_152);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_153);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_154);
    if(isLog4jEnabled){
    stringBuffer.append(TEXT_155);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_156);
    }
    stringBuffer.append(TEXT_157);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_158);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_159);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_160);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_161);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_162);
    if(!useGlob) {//perl5 mode not support windows(\) path separator at the mask string
    stringBuffer.append(TEXT_163);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_164);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_165);
    } else {
    stringBuffer.append(TEXT_166);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_167);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_168);
    }
    stringBuffer.append(TEXT_169);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_170);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_171);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_172);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_173);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_174);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_175);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_176);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_177);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_178);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_179);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_180);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_181);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_182);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_183);
    if(!useGlob) {
    stringBuffer.append(TEXT_184);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_185);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_186);
    }
    stringBuffer.append(TEXT_187);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_188);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_189);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_190);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_191);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_192);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_193);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_194);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_195);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_196);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_197);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_198);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_199);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_200);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_201);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_202);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_203);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_204);
    stringBuffer.append( cid );
    stringBuffer.append(TEXT_205);
    stringBuffer.append( cid );
    stringBuffer.append(TEXT_206);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_207);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_208);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_209);
    stringBuffer.append( cid );
    stringBuffer.append(TEXT_210);
    stringBuffer.append( cid );
    stringBuffer.append(TEXT_211);
    stringBuffer.append( cid );
    stringBuffer.append(TEXT_212);
    stringBuffer.append( cid );
    stringBuffer.append(TEXT_213);
    stringBuffer.append( cid );
    stringBuffer.append(TEXT_214);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_215);
    
                            if(("never".equals(overwrite) || "size_differ".equals(overwrite)) && !append){
                            
    stringBuffer.append(TEXT_216);
    stringBuffer.append( cid );
    stringBuffer.append(TEXT_217);
    stringBuffer.append( cid );
    stringBuffer.append(TEXT_218);
    stringBuffer.append( cid );
    stringBuffer.append(TEXT_219);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_220);
    stringBuffer.append( cid );
    stringBuffer.append(TEXT_221);
    
                            }
                             
    if(append){
    stringBuffer.append(TEXT_222);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_223);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_224);
    stringBuffer.append( cid );
    stringBuffer.append(TEXT_225);
    stringBuffer.append( cid );
    stringBuffer.append(TEXT_226);
    }else if(("never").equals(overwrite)){
    stringBuffer.append(TEXT_227);
    stringBuffer.append( cid );
    stringBuffer.append(TEXT_228);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_229);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_230);
    stringBuffer.append( cid );
    stringBuffer.append(TEXT_231);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_232);
    }else if(("always").equals(overwrite)){
    stringBuffer.append(TEXT_233);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_234);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_235);
    stringBuffer.append( cid );
    stringBuffer.append(TEXT_236);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_237);
    }else if(("size_differ").equals(overwrite)){
    stringBuffer.append(TEXT_238);
    stringBuffer.append( cid );
    stringBuffer.append(TEXT_239);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_240);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_241);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_242);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_243);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_244);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_245);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_246);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_247);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_248);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_249);
    stringBuffer.append( cid );
    stringBuffer.append(TEXT_250);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_251);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_252);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_253);
    stringBuffer.append( cid );
    stringBuffer.append(TEXT_254);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_255);
    }
    stringBuffer.append(TEXT_256);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_257);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_258);
    if(isLog4jEnabled){
    stringBuffer.append(TEXT_259);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_260);
    stringBuffer.append( cid );
    stringBuffer.append(TEXT_261);
    }
    stringBuffer.append(TEXT_262);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_263);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_264);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_265);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_266);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_267);
    stringBuffer.append( cid );
    stringBuffer.append(TEXT_268);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_269);
    if(isLog4jEnabled){
    stringBuffer.append(TEXT_270);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_271);
    }
    stringBuffer.append(TEXT_272);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_273);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_274);
    
    }else{// *** ftps *** //

    stringBuffer.append(TEXT_275);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_276);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_277);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_278);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_279);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_280);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_281);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_282);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_283);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_284);
    if(isLog4jEnabled){
    stringBuffer.append(TEXT_285);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_286);
    }
    stringBuffer.append(TEXT_287);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_288);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_289);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_290);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_291);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_292);
    if(!useGlob) {//perl5 mode not support windows(\) path separator at the mask string
    stringBuffer.append(TEXT_293);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_294);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_295);
    } else {
    stringBuffer.append(TEXT_296);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_297);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_298);
    }
    stringBuffer.append(TEXT_299);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_300);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_301);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_302);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_303);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_304);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_305);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_306);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_307);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_308);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_309);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_310);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_311);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_312);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_313);
    if(!useGlob) {
    stringBuffer.append(TEXT_314);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_315);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_316);
    }
    stringBuffer.append(TEXT_317);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_318);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_319);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_320);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_321);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_322);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_323);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_324);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_325);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_326);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_327);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_328);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_329);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_330);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_331);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_332);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_333);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_334);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_335);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_336);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_337);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_338);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_339);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_340);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_341);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_342);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_343);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_344);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_345);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_346);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_347);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_348);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_349);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_350);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_351);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_352);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_353);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_354);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_355);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_356);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_357);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_358);
    if("never".equals(ftpsoverwrite)){
    stringBuffer.append(TEXT_359);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_360);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_361);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_362);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_363);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_364);
    if(isLog4jEnabled){
    stringBuffer.append(TEXT_365);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_366);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_367);
    }
    stringBuffer.append(TEXT_368);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_369);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_370);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_371);
    }else if("always".equals(ftpsoverwrite)){
    stringBuffer.append(TEXT_372);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_373);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_374);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_375);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_376);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_377);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_378);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_379);
    if(isLog4jEnabled){
    stringBuffer.append(TEXT_380);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_381);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_382);
    }
    stringBuffer.append(TEXT_383);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_384);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_385);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_386);
    }
    stringBuffer.append(TEXT_387);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_388);
    if(isLog4jEnabled){
    stringBuffer.append(TEXT_389);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_390);
    }
    stringBuffer.append(TEXT_391);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_392);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_393);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_394);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_395);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_396);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_397);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_398);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_399);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_400);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_401);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_402);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_403);
    stringBuffer.append(cid );
    stringBuffer.append(TEXT_404);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_405);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_406);
    }
    stringBuffer.append(TEXT_407);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_408);
    
        if(("true").equals(dieOnError)){

    stringBuffer.append(TEXT_409);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_410);
    
        }else{

    if(isLog4jEnabled){
    stringBuffer.append(TEXT_411);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_412);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_413);
    }
    stringBuffer.append(TEXT_414);
    stringBuffer.append(cid);
    stringBuffer.append(TEXT_415);
    
        }

    stringBuffer.append(TEXT_416);
    stringBuffer.append(TEXT_417);
    return stringBuffer.toString();
  }
}
