package com.netapp.ads.repos;

import com.netapp.ads.models.Activity;
import com.netapp.ads.models.Preference;

import java.util.List;
import java.util.Set;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 28/01/2018
*/
@Repository
public interface ActivityRepository extends JpaRepository<Activity, Integer>, JpaSpecificationExecutor<Activity> {

	Set<Activity> findByDisposition(@Param("disposition") String disposition);
}
