package com.netapp.ads.repos;

import com.netapp.ads.models.AggregatePurpose;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;
import com.netapp.ads.models.AggregatePurposePK;

/**
* Generated by Spring Data Generator on 22/12/2017
*/
@Repository
public interface AggregatePurposeRepository extends JpaRepository<AggregatePurpose, AggregatePurposePK>, JpaSpecificationExecutor<AggregatePurpose> {

}
