package com.netapp.ads.repos;

import com.netapp.ads.models.AuditTrailNativeUser;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;
import com.netapp.ads.models.AuditTrailNativeUserPK;

/**
* Generated by Spring Data Generator on 22/12/2017
*/
@Repository
public interface AuditTrailNativeUserRepository extends JpaRepository<AuditTrailNativeUser, AuditTrailNativeUserPK>, JpaSpecificationExecutor<AuditTrailNativeUser> {

}
