package com.netapp.ads.repos;

import com.netapp.ads.models.Controller;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;
import com.netapp.ads.models.ControllerPK;

import java.util.List;

/**
 * Generated by Spring Data Generator on 22/12/2017
 */
@Repository
public interface ControllerRepository extends JpaRepository<Controller, ControllerPK>, JpaSpecificationExecutor<Controller> {
}
