package com.netapp.ads.repos;

import com.netapp.ads.models.ControllerRelease;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 28/01/2018
*/
@Repository
public interface ControllerReleaseRepository extends JpaRepository<ControllerRelease, Integer>, JpaSpecificationExecutor<ControllerRelease> {
	List<ControllerRelease> findByProcessedTrue();
	List<ControllerRelease> findByProcessedFalse();
}
