package com.netapp.ads.repos;

import com.netapp.ads.models.CutoverTime;
import com.netapp.ads.models.CutoverTimePK;
import com.netapp.ads.models.DataCenter;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 22/12/2017
*/
@Repository
public interface DataCenterRepository extends JpaRepository<DataCenter, Integer> {

}
