package com.netapp.ads.repos;

import com.netapp.ads.models.EmailTemplate;
import org.springframework.context.annotation.Scope;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 04/01/2018
*/
@Repository
//@Scope("prototype")
public interface EmailTemplateRepository extends JpaRepository<EmailTemplate, Integer> {
	public EmailTemplate findOneByTemplateName(String templateName);
}