package com.netapp.ads.repos;

import com.netapp.ads.models.Host;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 22/12/2017
*/
@Repository
public interface HostRepository extends JpaRepository<Host, Integer>, JpaSpecificationExecutor<Host> {

}
