package com.netapp.ads.repos;

import com.netapp.ads.models.MigrationProject;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 23/12/2017
*/
@Repository
public interface MigrationProjectRepository extends JpaRepository<MigrationProject, Integer>, JpaSpecificationExecutor<MigrationProject> {

}
