package com.netapp.ads.repos;

import com.netapp.ads.models.MigrationTime;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 23/12/2017
*/
@Repository
public interface MigrationTimeRepository extends JpaRepository<MigrationTime, Integer>, JpaSpecificationExecutor<MigrationTime> {

}
