package com.netapp.ads.repos;

import com.netapp.ads.models.MmsConfig;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 23/12/2017
*/
@Repository
public interface MmsConfigRepository extends JpaRepository<MmsConfig, Integer>, JpaSpecificationExecutor<MmsConfig> {

}
