package com.netapp.ads.repos;

import com.netapp.ads.models.NasVolume;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 19/01/2018
*/
@RepositoryRestResource
public interface NasVolumeRepository extends JpaRepository<NasVolume, Integer>, JpaSpecificationExecutor<NasVolume> {

}
