package com.netapp.ads.repos;

import com.netapp.ads.models.NasVolume;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
<<<<<<< HEAD
* Generated by Spring Data Generator on 19/01/2018
=======
* Generated by Spring Data Generator on 28/01/2018
>>>>>>> b_models_repos
*/
@Repository
public interface NasVolumeRepository extends JpaRepository<NasVolume, Integer>, JpaSpecificationExecutor<NasVolume> {

}
