package com.netapp.ads.repos;

import com.netapp.ads.models.Preference;
import com.netapp.ads.models.projections.PreferenceProjections;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 28/01/2018
*/
@RepositoryRestResource(excerptProjection=PreferenceProjections.class)
public interface PreferenceRepository extends JpaRepository<Preference, Integer>, JpaSpecificationExecutor<Preference> {

}
