package com.netapp.ads.repos;

import com.netapp.ads.models.Qtree;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 19/01/2018
*/
@Repository
public interface QtreeRepository extends JpaRepository<Qtree, Integer>, JpaSpecificationExecutor<Qtree> {

}
