package com.netapp.ads.repos;

import com.netapp.ads.models.Qtree;
import com.netapp.ads.models.QtreeDisposition;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 28/01/2018
*/
@Repository
public interface QtreeDispositionRepository extends JpaRepository<QtreeDisposition, Integer>, JpaSpecificationExecutor<Qtree> {
	
	List<QtreeDisposition> findByDisposition(@Param("disposition") String disposition);
	
	QtreeDisposition findOneByDispositionAndQtree(@Param("disposition") String disposition, @Param("qtree") Qtree qtree);
}
