package com.netapp.ads.repos;

import com.netapp.ads.models.Share;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 28/01/2018
*/
@Repository
public interface ShareRepository extends JpaRepository<Share, Integer>, JpaSpecificationExecutor<Share> {

	// FUTURE USE: Populate Activity table
//	@Query("SELECT COUNT(*) FROM share s JOIN qtree	ON qtree.id = s.qtree_id JOIN nas_volume ON qtree.nas_volume_id = nas_volume.id WHERE nas_volume.id = :nasVolumeId")
//    Long countOfSharesForOneVolume(@Param("nasVolumeId") int nasVolumeId);
}
