package com.netapp.ads.repos;

import com.netapp.ads.models.WorkPackage;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 28/01/2018
*/
@Repository
public interface WorkPackageRepository extends JpaRepository<WorkPackage, Integer>, JpaSpecificationExecutor<WorkPackage> {

}
