security:
  user:
    password: password
logging:
  level:
    org.springframework.security: DEBUG
    
spring:
    jpa.hibernate.ddl-auto: none
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/vitae_data_refactor
        username: root
        password: paragon1
