apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: ads-web
spec:
  selector:
    matchLabels:
      app: ads-web
  replicas: 2 # tells deployment to run 3 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: ads-web
    spec:
      containers:
      - name: ads-web
        image: ads-web:0.1
        imagePullPolicy: IfNotPresent # Get image locally
        ports:
        - containerPort: 8080
          name: ads-web-server
      nodeSelector:
        ads-type: web