package com.netapp.ads.repos;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.netapp.ads.models.LineOfBusiness;

/**
* Generated by Spring Data Generator on 28/01/2018
*/
@Repository
public interface LineOfBusinessRepository extends JpaRepository<LineOfBusiness, Integer>, JpaSpecificationExecutor<LineOfBusiness> {
	
	LineOfBusiness findByLobName(@Param("lobName") String lobName);
}
