package com.netapp.ads.repos;

import java.util.List;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.netapp.ads.models.SysConfig;

/**
* Generated by Spring Data Generator on 28/01/2018
*/
@Repository
public interface SysConfigRepository extends JpaRepository<SysConfig, Integer>, JpaSpecificationExecutor<SysConfig> {

	@Query("SELECT DISTINCT config.grouping FROM SysConfig config")
	List<String> findDistinctGroupNames();
	
	Page<SysConfig> findByGrouping(@Param("grouping") String grouping, Pageable p);
	
	SysConfig findByPropertyName(@Param("propertyName") String propertyName);
}
